[package]
name = "irpl"
version = "0.1.8-devel"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
chrono = "0.4.24"
clearscreen = "2.0.1"
easy-repl = { version = ">=0.2.3", git = "https://github.com/jgabaut/easy-repl" }
regex = "1.8.3"
