[package]
name = "irpl"
version = "0.1.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
easy-repl = "0.2.1"
regex = "1.8.3"
